#!/bin/bash

# Get the C file name from the environment variable
c_file_name="$CFILE"

# Generate the output file name (replace ".c" with ".s")
s_file_name="${c_file_name%.c}.s"

# Compile the C file to assembly code (Intel syntax)
gcc -S -masm=intel "$c_file_name" -o "$s_file_name"
